FROM node:alpine AS Builder

WORKDIR /usr/src/app

COPY  /package*.json ./

COPY .  .

RUN npm install -g @angular/cli

RUN npm install

RUN ng build

FROM nginx:alpine

COPY --from=builder /usr/src/app/dist/poker-planning-back/browser /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
