FROM node:19.5.0-alpine AS Builder
WORKDIR /usr/src/app

RUN npm install -g @angular/cli@17.2.0

COPY  /package*.json ./
RUN npm ci

COPY .  .

RUN ng build --output-path=dist/poker-planning-back/browser --configuration production

FROM node:19.5.0-alpine
WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/dist/poker-planning-back/browser  ./dist/poker-planning-back

# Copy server files
COPY server.js .
COPY package*.json .

# Install production dependencies
RUN npm install express prom-client --omit=dev

EXPOSE 80
CMD ["node", "server.js"]